Add service for notification email and reset password
cloudforet-io/identity pull request #32
Opened 2023-03-30 09:55 UTC by ImMin5

### Category
- [x] New feature
- [ ] Bug fix
- [x] Improvement
- [ ] Refactor
- [ ] etc

### Description

### Known issue
-  #31

2023-03-30 11:16 UTC, whdalsrnt requested changes
Hi, @ImMin5 

I reviewed the code you PR.
Please check the comments and change the code.

2023-03-30 11:16 UTC, whdalsrnt commented on src/spaceone/identity/conf/global_conf.py
> +        'temporary_token_timeout': 3600,
change key of token configurations
`temporary_token_timeout` -> `verify_code_timeout`

2023-03-30 11:16 UTC, whdalsrnt commented on src/spaceone/identity/error/error_user.py
> +class ERROR_PASSWORD_NOT_CHANGED(ERROR_UNABLE_TO_RESET_PASSWORD):
change the message to
`The requested password is the same as the previous password.`

2023-03-30 11:16 UTC, whdalsrnt commented on src/spaceone/identity/manager/email_manager.py
> +        if not os.path.exists(f'{TEMPLATE_PATH}/reset_password_link_{language}.html'):
Remove template validation logic

2023-03-30 11:16 UTC, whdalsrnt commented on src/spaceone/identity/manager/token_manager/__init__.py
> +        self.CONST_TEMPORARY_TOKEN_TIMEOUT = token_conf.get('temporary_token_timeout')
change variable name
`COST_TEMPROARY_TOKEN_TIMEOUT` -> `CONST_VERIFY_TOKEN_TIMEOUT`

2023-03-30 11:16 UTC, whdalsrnt commented on src/spaceone/identity/manager/token_manager/__init__.py
> +            verify_code = str(random.randint(100000, 999999))
separate the function that generates the verify code

2023-03-31 00:33 UTC, ImMin5 commented
Hi, @whdalsrnt 

Thank you for your review. 
I have applied your feedback and made the necessary changes. 
Would you please take a look at the updated version and let me know if there is anything else I can do to improve it.

2023-03-31 01:55 UTC, whdalsrnt requested changes

2023-03-31 01:55 UTC, whdalsrnt commented on src/spaceone/identity/connector/smtp_connector.py
> +        self.smtp.ehlo()
Please remove duplicate code. 
`self.smtp.ehlo()`

2023-03-31 01:55 UTC, whdalsrnt commented on src/spaceone/identity/manager/email_manager.py
> +        subject = '[SpaceONE] Verify your email address'
Please change the email subject and contents to be configurable.
- Location: `global_conf.py`
- Default: `Cloudforet`

2023-03-31 01:55 UTC, whdalsrnt commented on src/spaceone/identity/manager/token_manager/__init__.py
> +    def generate_verify_code(self, domain_id, user_id):
Duplicate function name below.
Please change it to `create_verify_code`.

2023-03-31 04:09 UTC, ImMin5 commented
Hi, @whdalsrnt 
Thanks for spend time for review, I applied what you suggested.

2023-03-31 05:27 UTC, whdalsrnt approved these changes
Hi, @ImMin5 
Thanks for the quick change to the feedback.

2023-03-31 05:27 UTC, merged